quant_config:
  algo: gptq
  kwargs:
    w_dtype: int4    # select from ['int2', 'int3', 'int4', 'int8', 'float16']
    a_dtype: float16
    device: 'cuda'
    offload: 'cpu'
    blocksize: 128 
    percdamp: .01
    actorder: True
    w_groupsize: -1        
    w_qtype: "per_channel"  #select from ['per_channel', 'per_group']                    
    block_sequential: True
    layer_sequential: True
    skip_layers:                   # the linear layer to skip, should match the module name
      - lm_head
  calibrate_config:
    name: 'wikitext2'
    split: train
    nsample: 1
    seqlen: 2048