quant_config:
  algo: rtn
  kwargs:
    model_type: "llama"
    w_dtype: int8    # select from ['int2', 'int3', 'int4', 'fp4', 'int8', 'fp8', 'float16']
    a_dtype: int8   # select from ['int2', 'int3', 'int4', 'fp4', 'int8', 'fp8', 'float16']
    calibrate_seq_length: 2048
    device: 'cuda'
    offload: 'cpu'
    w_groupsize: -1
    a_groupsize: -1
    a_qtype: "per_tensor"              
    w_qtype: "per_channel"             
    w_has_zero: False
    a_has_zero: False
    w_unsign: True
    a_unsign: True
    quantization_type: 'static'
    block_sequential: True
    layer_sequential: True
    skip_layers:                   # the linear layer to skip, should match the module name
      - lm_hea
  calibrate_config:
    name: 'ceval'
    split: test
    calibrate_subject: all
    calibrate_nums: 4 
    calibrate_seqlen: 2048
    shuffle: False
  